version: '3'

services:
  app:
    build: .
    ports:
      - "8080:5661"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: db_bakka
      POSTGRES_USER: dijany
      POSTGRES_PASSWORD: Artisans2022!
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: